
IF(${CMAKE_SYSTEM_NAME} MATCHES "Windows")
	INCLUDE(${MARLIN_MAIN_DIRECTORY}/.BuildFiles/VCXProjFormatter.cmake)
ENDIF(${CMAKE_SYSTEM_NAME} MATCHES "Windows")

IF (NOT ${CMAKE_SYSTEM_NAME} MATCHES "Windows")
    ADD_DEFINITIONS(-std=c++1y)
	ADD_DEFINITIONS(-DBOOST_LOG_DYN_LINK)
ELSE(NOT ${CMAKE_SYSTEM_NAME} MATCHES "Windows")
	ADD_DEFINITIONS(-D_WIN32_WINNT=0x0600)
	ADD_DEFINITIONS(-D_XKEYCHECK_H)
	ADD_DEFINITIONS(/MP)
ENDIF (NOT ${CMAKE_SYSTEM_NAME} MATCHES "Windows")
MESSAGE("BOOST_INCLUDE: $ENV{BOOST_INCLUDE}")
SET(BOOST_INCLUDEDIR $ENV{BOOST_INCLUDE})

#SET(Boost_DEBUG ON)

SET( Boost_USE_STATIC_LIBS ON )

FIND_PACKAGE(Boost)

MESSAGE("Boost_INCLUDE_DIRS: ${Boost_INCLUDE_DIRS}")
MESSAGE("Boost_LIBRARY_DIRS: ${Boost_LIBRARY_DIRS}")

IF( ENABLE_COVERAGE )
    SET( CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fprofile-arcs -ftest-coverage" )
    SET( CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fprofile-arcs -ftest-coverage" )
    SET( GCOV_LIB gcov )
ENDIF( ENABLE_COVERAGE )

SET(CMAKE_INSTALL_PREFIX ${PROJECT_SOURCE_DIR})

ADD_DEFINITIONS(-DPTHREADS -D_REENTRANT)

SET(MARLIN_SOURCE_DIR ${MARLIN_MAIN_DIRECTORY}/src)

SET(MARLIN_TEST_DIR ${MARLIN_MAIN_DIRECTORY}/test)

IF(${CMAKE_SYSTEM_NAME} MATCHES "Windows")
	ADD_DEFINITIONS(-DLITTLE_ENDIAN)
ENDIF(${CMAKE_SYSTEM_NAME} MATCHES "Windows")

FILE(GLOB_RECURSE  SOURCE1 
	${PROJECT_SOURCE_DIR}/*.cpp
	${PROJECT_SOURCE_DIR}/*.h
)

FILE(GLOB_RECURSE REMOVE_SOURCE1 
	${PROJECT_SOURCE_DIR}/build/*.cpp
	${PROJECT_SOURCE_DIR}/build/*.h
)

IF(REMOVE_SOURCE1)
	list(REMOVE_ITEM SOURCE1 ${REMOVE_SOURCE1})
ENDIF(REMOVE_SOURCE1)

FILE(GLOB_RECURSE SOURCE2
	${MARLIN_SOURCE_DIR}/MarlinApp.cpp
	${MARLIN_SOURCE_DIR}/MarlinConfiguration.cpp
	${MARLIN_SOURCE_DIR}/RTI/*.cpp
	${MARLIN_SOURCE_DIR}/PLI/*.cpp
	${MARLIN_SOURCE_DIR}/ICD/*.cpp
	${MARLIN_SOURCE_DIR}/LLC/*.cpp
	${MARLIN_SOURCE_DIR}/MAN/*.cpp
	${MARLIN_SOURCE_DIR}/MAC/*.cpp
	${MARLIN_SOURCE_DIR}/PI/*.cpp
	${MARLIN_SOURCE_DIR}/RC/*.cpp
	${MARLIN_SOURCE_DIR}/Mediator/*.cpp
	${MARLIN_SOURCE_DIR}/MarlinDDSTypes/*.cpp
	${MARLIN_SOURCE_DIR}/DDSCommunicators/*.cpp
	${MARLIN_SOURCE_DIR}/MMI/*.cpp
	${MARLIN_SOURCE_DIR}/Util/*.cpp
)

#MESSAGE("#######################################################################")
#MESSAGE(" # Source3 List")
#FOREACH(CPPFILE ${SOURCE1})
#MESSAGE("${CPPFILE}")
#ENDFOREACH(CPPFILE)
#FOREACH(CPPFILE ${SOURCE2})
#MESSAGE("${CPPFILE}")
#ENDFOREACH(CPPFILE)
#MESSAGE("##################################################################")

IF(${CMAKE_SYSTEM_NAME} MATCHES "Windows")
	GroupSources(${MARLIN_MAIN_DIRECTORY} src)
ENDIF(${CMAKE_SYSTEM_NAME} MATCHES "Windows")

SET (DDSI $ENV{DDS_INCLUDE})
SET (DDSL $ENV{DDS_LIB})
SET (PROCESSFRAMEWORKL $ENV{PROCESSFRAMEWORK_LIB})
SET (PROCESSFRAMEWORKI $ENV{PROCESSFRAMEWORK_INCLUDE})

IF ( ${CMAKE_SYSTEM_NAME} MATCHES "Windows")
	SET (RMSSCI $ENV{RMSSC_INCLUDE})
    SET (RMSSCL $ENV{RMSSC_LIB})
	SET (PCAPI $ENV{PCAP_INCLUDE})
	SET (PCAPL $ENV{PCAP_LIB})
ENDIF ( ${CMAKE_SYSTEM_NAME} MATCHES "Windows")

IF(${CMAKE_BUILD_TYPE} MATCHES "Debug")
	SET (BUILD_TYPE_SUFFIX d)
ENDIF(${CMAKE_BUILD_TYPE} MATCHES "Debug")

MESSAGE("BUILD_TYPE_SUFFIX : ${BUILD_TYPE_SUFFIX}")

INCLUDE_DIRECTORIES(
	${PROJECT_SOURCE_DIR}
	${MARLIN_SOURCE_DIR}
	${MARLIN_TEST_DIR}
	${Boost_INCLUDE_DIRS}
	$ENV{CPPUNIT_INCLUDE}
	${PCAPI}
	${RMSSCI}
	${PROCESSFRAMEWORKI}
	${DDSI}
)

LINK_DIRECTORIES(
    ${Boost_LIBRARY_DIRS}
	$ENV{CPPUNIT_LIB}
    ${PCAPL}
    ${RMSSCL}
	${DDSL}
	${PROCESSFRAMEWORKL}
)

ADD_EXECUTABLE(${UNIT_NAME} ${SOURCE1} ${SOURCE2} ${MARLIN_MAIN_DIRECTORY}/.BuildFiles/TestRunner.cpp)

SET(PCAP pcap)

IF(NOT ${CMAKE_SYSTEM_NAME} MATCHES "Windows")
	SET(NSL nsl)
	SET(PTHREAD pthread)
	SET(DL dl)
    SET (ROHC_COMP rohc_comp)
    SET (ROHC_DECOMP rohc_decomp)
    SET (RT rt)
	SET (GPS gps)
ENDIF (NOT ${CMAKE_SYSTEM_NAME} MATCHES "Windows")

IF(${CMAKE_SYSTEM_NAME} MATCHES "Windows")
	IF(${CMAKE_BUILD_TYPE} MATCHES "Release")
		SET (BOOST_ABI_TAG ${_boost_RELEASE_ABI_TAG})
	ELSE(${CMAKE_BUILD_TYPE} MATCHES "Release")
		SET (BOOST_ABI_TAG ${_boost_DEBUG_ABI_TAG})
		SET (CPPUNIT_SUFFIX d)
	ENDIF(${CMAKE_BUILD_TYPE} MATCHES "Release")
	
    SET (BOOST_PREFIX lib)
    SET (BOOST_SUFFIX ${_boost_COMPILER}${_boost_MULTITHREADED}${BOOST_ABI_TAG}-${Boost_LIB_VERSION})
    SET (PCAP_PREFIX w)
	SET (RMSSC rm_sc_dll)
ENDIF(${CMAKE_SYSTEM_NAME} MATCHES "Windows")

SET(LINK_LIBRARIES_VAR
    ${BOOST_PREFIX}boost_thread${BOOST_SUFFIX}
    ${BOOST_PREFIX}boost_system${BOOST_SUFFIX}
    ${BOOST_PREFIX}boost_filesystem${BOOST_SUFFIX}
    ${BOOST_PREFIX}boost_date_time${BOOST_SUFFIX}
    ${BOOST_PREFIX}boost_log_setup${BOOST_SUFFIX}
    ${BOOST_PREFIX}boost_log${BOOST_SUFFIX}
    ${BOOST_PREFIX}boost_iostreams${BOOST_SUFFIX}
    ${BOOST_PREFIX}boost_program_options${BOOST_SUFFIX}
    ${PCAP_PREFIX}${PCAP}
    ${NSL}
    ${PTHREAD}
    ${GPS}
    ${DL}
    ${ROHC_COMP}
    ${ROHC_DECOMP}
    ${GCOV_LIB}
    cppunit${CPPUNIT_SUFFIX}
	${RMSSC}
	DDSs${BUILD_TYPE_SUFFIX}
	ProcessFrameworks${BUILD_TYPE_SUFFIX}
	${RT}
)

TARGET_LINK_LIBRARIES(
    ${UNIT_NAME}
	${LINK_LIBRARIES_VAR}
)

INSTALL(TARGETS ${UNIT_NAME} DESTINATION build)
